export default {
    start: 'start',
    pre_input_stage: "pre_input_stage",
    age_input: "age_input",
    city_input: "city_input",
    description_input: "description_input",
    image_input: "image_input",
    city_input: "city_input",
    preferred_gender_input: "preferred_gender_input",
    gender_input: "gender_input",
    finished: "finished",
    name_input: "name_input",
    review_profile: "review_profile",
    in_settings: "in_settings",
}