version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
  es:
    image: elasticsearch:8.4.0
    restart: always
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - xpack.security.enabled=false